#!/bin/sh
set -eu

BACKUP_ROOT=${BOOKKIN_BACKUP_DIR:-./.local/backups}
STAMP=$(date -u +%Y%m%dT%H%M%SZ)
DESTINATION="$BACKUP_ROOT/$STAMP"
mkdir -p "$DESTINATION"

docker compose exec -T postgres pg_dump \
  --username "${POSTGRES_USER:-bookkin}" \
  --dbname "${POSTGRES_DB:-bookkin}" \
  --format custom > "$DESTINATION/database.dump"

LIBRARY_ROOTS=${BOOKKIN_LIBRARY_BACKUP_ROOTS:-${BOOKKIN_LIBRARY_MAIN:-./.local/library}}
CHECKSUM_FILES="database.dump"
ROOT_INDEX=0
OLD_IFS=$IFS
IFS=:
for LIBRARY_ROOT in $LIBRARY_ROOTS; do
  ARCHIVE="recoverable-root-$ROOT_INDEX.tar.gz"
  ENTRIES=""
  if [ -d "$LIBRARY_ROOT/.bookkin-trash" ]; then ENTRIES="$ENTRIES .bookkin-trash"; fi
  if [ -n "$ENTRIES" ]; then
    IFS=$OLD_IFS
    # shellcheck disable=SC2086
    set -- $ENTRIES
    tar -C "$LIBRARY_ROOT" -czf "$DESTINATION/$ARCHIVE" "$@"
    IFS=:
    CHECKSUM_FILES="$CHECKSUM_FILES $ARCHIVE"
  fi
  ROOT_INDEX=$((ROOT_INDEX + 1))
done
IFS=$OLD_IFS

# Filenames are generated by this script and contain no whitespace.
# shellcheck disable=SC2086
set -- $CHECKSUM_FILES
if command -v sha256sum >/dev/null 2>&1; then
  (cd "$DESTINATION" && sha256sum "$@") > "$DESTINATION/SHA256SUMS"
else
  (cd "$DESTINATION" && shasum -a 256 "$@") > "$DESTINATION/SHA256SUMS"
fi
echo "Backup written to $DESTINATION"
